# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/chatmessage.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import event_pb2 as proto_dot_event__pb2
from proto import execution_pb2 as proto_dot_execution__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/chatmessage.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17proto/chatmessage.proto\x1a\x11proto/event.proto\x1a\x15proto/execution.proto\"A\n\nroomstatus\x12\x0e\n\x06roomid\x18\x01 \x02(\x05\x12\x10\n\x08maxusers\x18\x02 \x02(\r\x12\x11\n\tcurrusers\x18\x03 \x03(\t\"\x8a\x02\n\x0b\x63hatmessage\x12\x17\n\x05mtype\x18\x01 \x02(\x0e\x32\x08.msgtype\x12\x12\n\nuserstatus\x18\x02 \x01(\t\x12\x10\n\x08numrooms\x18\x03 \x01(\r\x12\x1a\n\x05rooms\x18\x04 \x03(\x0b\x32\x0b.roomstatus\x12\x0c\n\x04user\x18\x05 \x01(\t\x12\x0e\n\x06roomid\x18\x06 \x01(\x05\x12\x0f\n\x07\x63omment\x18\x07 \x01(\t\x12\x1a\n\x0csport_filter\x18\x08 \x01(\t:\x04SAME\x12\x1e\n\x10\x65xecution_filter\x18\t \x01(\t:\x04SAME\x12\x18\n\x08\x65ventmsg\x18\n \x01(\x0b\x32\x06.event\x12\x1b\n\x07\x65xecmsg\x18\x0b \x01(\x0b\x32\n.execution*[\n\x07msgtype\x12\x0f\n\x0bROOM_STATUS\x10\x01\x12\x0c\n\x08JOIN_REQ\x10\x02\x12\x0b\n\x07\x43OMMENT\x10\x03\x12\n\n\x06\x46ILTER\x10\x04\x12\t\n\x05\x45VENT\x10\x05\x12\r\n\tEXECUTION\x10\x06'
  ,
  dependencies=[proto_dot_event__pb2.DESCRIPTOR,proto_dot_execution__pb2.DESCRIPTOR,])

_MSGTYPE = _descriptor.EnumDescriptor(
  name='msgtype',
  full_name='msgtype',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ROOM_STATUS', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JOIN_REQ', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMENT', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FILTER', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVENT', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXECUTION', index=5, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=405,
  serialized_end=496,
)
_sym_db.RegisterEnumDescriptor(_MSGTYPE)

msgtype = enum_type_wrapper.EnumTypeWrapper(_MSGTYPE)
ROOM_STATUS = 1
JOIN_REQ = 2
COMMENT = 3
FILTER = 4
EVENT = 5
EXECUTION = 6



_ROOMSTATUS = _descriptor.Descriptor(
  name='roomstatus',
  full_name='roomstatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='roomid', full_name='roomstatus.roomid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxusers', full_name='roomstatus.maxusers', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currusers', full_name='roomstatus.currusers', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=134,
)


_CHATMESSAGE = _descriptor.Descriptor(
  name='chatmessage',
  full_name='chatmessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mtype', full_name='chatmessage.mtype', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userstatus', full_name='chatmessage.userstatus', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numrooms', full_name='chatmessage.numrooms', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rooms', full_name='chatmessage.rooms', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='chatmessage.user', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roomid', full_name='chatmessage.roomid', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='chatmessage.comment', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sport_filter', full_name='chatmessage.sport_filter', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"SAME".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='execution_filter', full_name='chatmessage.execution_filter', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"SAME".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventmsg', full_name='chatmessage.eventmsg', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='execmsg', full_name='chatmessage.execmsg', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=403,
)

_CHATMESSAGE.fields_by_name['mtype'].enum_type = _MSGTYPE
_CHATMESSAGE.fields_by_name['rooms'].message_type = _ROOMSTATUS
_CHATMESSAGE.fields_by_name['eventmsg'].message_type = proto_dot_event__pb2._EVENT
_CHATMESSAGE.fields_by_name['execmsg'].message_type = proto_dot_execution__pb2._EXECUTION
DESCRIPTOR.message_types_by_name['roomstatus'] = _ROOMSTATUS
DESCRIPTOR.message_types_by_name['chatmessage'] = _CHATMESSAGE
DESCRIPTOR.enum_types_by_name['msgtype'] = _MSGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

roomstatus = _reflection.GeneratedProtocolMessageType('roomstatus', (_message.Message,), {
  'DESCRIPTOR' : _ROOMSTATUS,
  '__module__' : 'proto.chatmessage_pb2'
  # @@protoc_insertion_point(class_scope:roomstatus)
  })
_sym_db.RegisterMessage(roomstatus)

chatmessage = _reflection.GeneratedProtocolMessageType('chatmessage', (_message.Message,), {
  'DESCRIPTOR' : _CHATMESSAGE,
  '__module__' : 'proto.chatmessage_pb2'
  # @@protoc_insertion_point(class_scope:chatmessage)
  })
_sym_db.RegisterMessage(chatmessage)


# @@protoc_insertion_point(module_scope)
